name: Fetch AR libs (via checkout)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      # Dein Repo
      - uses: actions/checkout@v4

      # A-Frame v1.4.0 direkt aus dem offiziellen Repo holen
      - name: Checkout A-Frame
        uses: actions/checkout@v4
        with:
          repository: aframevr/aframe
          ref: v1.4.0
          path: vendor/aframe

      # MindAR 1.2.5 direkt aus dem offiziellen Repo holen
      - name: Checkout MindAR
        uses: actions/checkout@v4
        with:
          repository: hiukim/mind-ar-js
          ref: 1.2.5
          path: vendor/mindar

      # Dateien in dein Repo kopieren
      - name: Copy libs + demo
        run: |
          set -euxo pipefail
          mkdir -p lib demo
          echo "" > .nojekyll

          # A-Frame
          cp -v vendor/aframe/dist/aframe.min.js lib/aframe.min.js

          # MindAR (Adapter + Worker + WASM)
          cp -v vendor/mindar/dist/mindar-image-aframe.prod.js lib/mindar-image-aframe.prod.js
          cp -v vendor/mindar/dist/mindar-image-worker.js     lib/mindar-image-worker.js
          cp -v vendor/mindar/dist/mindar-image-wasm.wasm     lib/mindar-image-wasm.wasm

          # Demo-Marker
          cp -v vendor/mindar/examples/image-tracking/assets/card-example/card.mind demo/card.mind
          cp -v vendor/mindar/examples/image-tracking/assets/card-example/card.png  demo/card.png

      # PR statt Direkt-Push (funktioniert auch mit geschütztem main)
      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add local AR libs (A-Frame v1.4.0 + MindAR 1.2.5) and demo marker"
          title: "Add local AR libs"
          body: "Files copied via actions/checkout from upstream repos. Adds /lib, /demo and .nojekyll."
          branch: chore/add-ar-libs
          delete-branch: true
