name: Fetch AR libs (zip tags)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          set -euxo pipefail
          mkdir -p lib demo tmp
          echo "" > .nojekyll

      - name: Download release ZIPs from github.com
        run: |
          set -euxo pipefail
          curl -L --fail "https://github.com/aframevr/aframe/archive/refs/tags/v1.4.0.zip" -o tmp/aframe.zip
          curl -L --fail "https://github.com/hiukim/mind-ar-js/archive/refs/tags/1.2.5.zip" -o tmp/mindar.zip

      - name: Unzip and copy files
        run: |
          set -euxo pipefail
          unzip -q tmp/aframe.zip -d tmp/aframe
          unzip -q tmp/mindar.zip -d tmp/mindar
          # A-Frame
          cp -v tmp/aframe/aframe-1.4.0/dist/aframe.min.js lib/aframe.min.js
          # MindAR (Adapter + Worker + WASM)
          cp -v tmp/mindar/mind-ar-js-1.2.5/dist/mindar-image-aframe.prod.js lib/mindar-image-aframe.prod.js
          cp -v tmp/mindar/mind-ar-js-1.2.5/dist/mindar-image-worker.js     lib/mindar-image-worker.js
          cp -v tmp/mindar/mind-ar-js-1.2.5/dist/mindar-image-wasm.wasm     lib/mindar-image-wasm.wasm
          # Demo marker
          cp -v tmp/mindar/mind-ar-js-1.2.5/examples/image-tracking/assets/card-example/card.mind demo/card.mind
          cp -v tmp/mindar/mind-ar-js-1.2.5/examples/image-tracking/assets/card-example/card.png  demo/card.png

      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add local AR libs (A-Frame 1.4.0 + MindAR 1.2.5) and demo marker"
          title: "Add local AR libs"
          body: "Copies from official tag ZIPs on github.com. Adds /lib, /demo and .nojekyll."
          branch: chore/add-ar-libs
          delete-branch: true
