name: Fetch AR libs (robust)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          set -euxo pipefail
          mkdir -p lib demo
          echo "" > .nojekyll

      - name: Download libs with fallbacks
        run: |
          set -euxo pipefail

          get () {
            dest="$1"; shift
            for url in "$@"; do
              echo "→ trying $url"
              if curl -fsSL --retry 5 --retry-delay 2 "$url" -o "$dest"; then
                echo "✓ saved $dest from $url"
                return 0
              fi
              echo "… failed $url"
            done
            echo "✗ could not fetch $dest"; exit 1
          }

          # A-Frame (mehrere Mirrors)
          get lib/aframe.min.js \
            "https://aframe.io/releases/1.4.0/aframe.min.js" \
            "https://raw.githubusercontent.com/aframevr/aframe/v1.4.0/dist/aframe.min.js"

          # MindAR Adapter/Worker/WASM (mit Fallback auf raw.githubusercontent)
          get lib/mindar-image-aframe.prod.js \
            "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-aframe.prod.js" \
            "https://raw.githubusercontent.com/hiukim/mind-ar-js/1.2.5/dist/mindar-image-aframe.prod.js"

          get lib/mindar-image-worker.js \
            "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-worker.js" \
            "https://raw.githubusercontent.com/hiukim/mind-ar-js/1.2.5/dist/mindar-image-worker.js"

          get lib/mindar-image-wasm.wasm \
            "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-wasm.wasm" \
            "https://raw.githubusercontent.com/hiukim/mind-ar-js/1.2.5/dist/mindar-image-wasm.wasm"

          # Demo-Marker
          get demo/card.mind \
            "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/card.mind" \
            "https://raw.githubusercontent.com/hiukim/mind-ar-js/1.2.5/examples/image-tracking/assets/card-example/card.mind"

          get demo/card.png \
            "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/card.png" \
            "https://raw.githubusercontent.com/hiukim/mind-ar-js/1.2.5/examples/image-tracking/assets/card-example/card.png"

      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add local AR libs (/lib) & demo marker (/demo) + .nojekyll"
          title: "Add local AR libs"
          body: "Downloaded with multi-source fallbacks (aframe.io, jsDelivr, raw.githubusercontent)."
          branch: chore/add-ar-libs
          delete-branch: true
