name: Fetch AR libs

on:
  workflow_dispatch:

permissions:
  contents: write        # erlaubt dem Workflow Änderungen zu committen
  pull-requests: write   # erlaubt dem Workflow eine PR zu erstellen

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make folders
        run: |
          mkdir -p lib demo
          echo "" > .nojekyll

      - name: Fetch A-Frame + MindAR + Demo marker
        run: |
          set -e
          # A-Frame (stabil mit MindAR)
          curl -L --fail "https://aframe.io/releases/1.4.0/aframe.min.js" -o lib/aframe.min.js
          # MindAR (Adapter + Worker + WASM) – GitHub-Mirror
          curl -L --fail "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-aframe.prod.js" -o lib/mindar-image-aframe.prod.js
          curl -L --fail "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-worker.js"     -o lib/mindar-image-worker.js
          curl -L --fail "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/dist/mindar-image-wasm.wasm"     -o lib/mindar-image-wasm.wasm
          # Demo-Marker
          curl -L --fail "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/card.mind" -o demo/card.mind
          curl -L --fail "https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/card.png"  -o demo/card.png

      # ⬇️ Statt direkt zu pushen, erstellen wir eine Pull Request
      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add AR libs: /lib (aframe+mindar) & /demo (card)"
          title: "Add AR libs to repo"
          body: "Adds local copies of A-Frame & MindAR (adapter/worker/wasm) and demo marker, plus .nojekyll."
          branch: chore/add-ar-libs
          delete-branch: true
