name: Fetch AR libs (npm tarballs)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make folders
        run: |
          set -e
          mkdir -p lib demo tmp
          echo "" > .nojekyll

      - name: Download tarballs from npm
        run: |
          set -euxo pipefail
          curl -L --fail "https://registry.npmjs.org/aframe/-/aframe-1.4.0.tgz" -o tmp/aframe.tgz
          curl -L --fail "https://registry.npmjs.org/mind-ar/-/mind-ar-1.2.5.tgz" -o tmp/mindar.tgz

      - name: Extract and copy needed files
        run: |
          set -euxo pipefail
          tar -xzf tmp/aframe.tgz -C tmp
          tar -xzf tmp/mindar.tgz -C tmp
          # A-Frame
          cp -v tmp/package/dist/aframe.min.js lib/aframe.min.js
          # MindAR (A-Frame adapter + worker + wasm)
          cp -v tmp/package/dist/mindar-image-aframe.prod.js lib/mindar-image-aframe.prod.js
          cp -v tmp/package/dist/mindar-image-worker.js     lib/mindar-image-worker.js
          cp -v tmp/package/dist/mindar-image-wasm.wasm     lib/mindar-image-wasm.wasm
          # Demo marker
          cp -v tmp/package/examples/image-tracking/assets/card-example/card.mind demo/card.mind
          cp -v tmp/package/examples/image-tracking/assets/card-example/card.png  demo/card.png

      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add AR libs from npm tarballs: /lib and /demo (+.nojekyll)"
          title: "Add local AR libraries (A-Frame + MindAR) and demo marker"
          body: "Files pulled from npm tarballs to avoid flaky CDNs. Adds /lib (aframe+mindar) and /demo (card)."
          branch: chore/add-ar-libs
          delete-branch: true
