name: Fetch AR libs (npm pack)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node (for npm pack)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch from npm tarballs
        run: |
          set -euxo pipefail
          mkdir -p lib demo tmp
          echo "" > .nojekyll
          cd tmp
          # Pack tarballs from npm (stable)
          AF_TGZ=$(npm pack aframe@1.4.0 | tail -n1)
          MA_TGZ=$(npm pack mind-ar@1.2.5 | tail -n1)
          mkdir aframe mindar
          tar -xzf "$AF_TGZ" -C aframe
          tar -xzf "$MA_TGZ" -C mindar
          # Copy libs
          cp -v aframe/package/dist/aframe.min.js                           ../lib/aframe.min.js
          cp -v mindar/package/dist/mindar-image-aframe.prod.js             ../lib/mindar-image-aframe.prod.js
          cp -v mindar/package/dist/mindar-image-worker.js                  ../lib/mindar-image-worker.js
          cp -v mindar/package/dist/mindar-image-wasm.wasm                  ../lib/mindar-image-wasm.wasm
          # Demo marker
          cp -v mindar/package/examples/image-tracking/assets/card-example/card.mind ../demo/card.mind
          cp -v mindar/package/examples/image-tracking/assets/card-example/card.png  ../demo/card.png
          cd ..

      - name: Create PR with fetched files
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add local AR libs (A-Frame 1.4.0 + MindAR 1.2.5) and demo marker"
          title: "Add local AR libs"
          body: "Libraries added via npm pack. Adds /lib, /demo and .nojekyll."
          branch: chore/add-ar-libs
          delete-branch: true
